use std::path::{Path, PathBuf};
use std::process::Command;
use std::time::{SystemTime, UNIX_EPOCH};

use anyhow::{bail, Context, Result};
use base64::{engine::general_purpose::STANDARD as B64, Engine as _};
use clap::{Args, Parser, Subcommand};
use mermaid_rs_renderer::{render_with_options, RenderOptions};
use pulldown_cmark::{Event, Options, Parser as MdParser, Tag, TagEnd};
use ratex_layout::{layout, to_display_list, LayoutOptions};
use ratex_parser::parser::parse as parse_latex;
use ratex_svg::{render_to_svg, SvgOptions};
use ratex_types::math_style::MathStyle;
use syntect::easy::HighlightLines;
use syntect::highlighting::ThemeSet;
use syntect::html::{styled_line_to_highlighted_html, IncludeBackground};
use syntect::parsing::SyntaxSet;

#[derive(Parser, Debug)]
#[command(
    name = "pagemd",
    about = "Convert Markdown to a self-contained single HTML file",
    long_about = None,
)]
struct Cli {
    #[command(subcommand)]
    command: Option<Commands>,

    #[command(flatten)]
    args: CliArgs,
}

#[derive(Subcommand, Debug)]
enum Commands {
    #[command(about = "Convert Markdown and open the generated HTML in the default browser")]
    View(CliArgs),
}

#[derive(Args, Debug, Clone)]
struct CliArgs {
    #[arg(short = 'i', long = "input", value_name = "FILE", num_args = 1..)]
    inputs: Vec<PathBuf>,

    #[arg(short = 'o', long = "output", value_name = "FILE")]
    output: Option<PathBuf>,

    #[arg(long = "title", value_name = "TITLE")]
    title: Option<String>,

    #[arg(long = "font-size", default_value = "16")]
    math_font_size: f64,

    #[arg(long = "katex-fonts", value_name = "DIR", help = "Directory containing KaTeX .ttf font files for glyph embedding")]
    katex_fonts: Option<PathBuf>,
}

fn find_katex_fonts(hint: Option<&Path>) -> Result<String> {
    if let Some(p) = hint {
        if p.join("KaTeX_Main-Regular.ttf").exists() {
            return Ok(p.to_string_lossy().into_owned());
        }
        bail!("KaTeX fonts not found in {}", p.display());
    }

    let bundled = option_env!("PAGEMD_KATEX_FONT_DIR")
        .context("Bundled KaTeX font path was not generated by build.rs")?;
    let bundled_path = Path::new(bundled);
    if bundled_path.join("KaTeX_Main-Regular.ttf").exists() {
        return Ok(bundled_path.to_string_lossy().into_owned());
    }

    bail!("Bundled KaTeX fonts not found in {}", bundled_path.display())
}

fn latex_to_svg(expr: &str, display: bool, font_size: f64, font_dir: &str) -> Result<String> {
    let ast = parse_latex(expr).map_err(|e| anyhow::anyhow!("LaTeX parse error: {}", e))?;
    let style = if display { MathStyle::Display } else { MathStyle::Text };
    let opts = LayoutOptions {
        style,
        ..LayoutOptions::default()
    };
    let lbox = layout(&ast, &opts);
    let dl = to_display_list(&lbox);
    let embed = !font_dir.is_empty();
    let svg_opts = SvgOptions {
        font_size: font_size * 2.5,
        padding: 2.0,
        stroke_width: 1.5,
        embed_glyphs: embed,
        font_dir: font_dir.to_owned(),
    };
    Ok(render_to_svg(&dl, &svg_opts))
}

fn render_mermaid(code: &str) -> Result<String> {
    let opts = RenderOptions::modern()
        .with_node_spacing(60.0)
        .with_rank_spacing(80.0);
    let svg = render_with_options(code.trim(), opts).context("Failed to render Mermaid diagram")?;
    Ok(format!("<div class=\"mermaid-display\"><div class=\"mermaid-canvas\">{svg}</div></div>\n"))
}

fn mermaid_error_html(code: &str) -> String {
    format!(
        "<div class=\"mermaid-display mermaid-error\"><strong>Mermaid render failed</strong><pre><code>{}</code></pre></div>\n",
        html_escape(code)
    )
}

fn image_to_data_uri(src: &str, base_dir: &Path) -> String {
    let path = if src.starts_with("http://") || src.starts_with("https://") {
        return src.to_string();
    } else if src.starts_with('/') {
        PathBuf::from(src)
    } else {
        base_dir.join(src)
    };

    match std::fs::read(&path) {
        Ok(data) => {
            let mime = mime_from_ext(path.extension().and_then(|e| e.to_str()).unwrap_or(""));
            format!("data:{};base64,{}", mime, B64.encode(&data))
        }
        Err(_) => src.to_string(),
    }
}

fn mime_from_ext(ext: &str) -> &'static str {
    match ext.to_lowercase().as_str() {
        "png" => "image/png",
        "jpg" | "jpeg" => "image/jpeg",
        "gif" => "image/gif",
        "webp" => "image/webp",
        "svg" => "image/svg+xml",
        "ico" => "image/x-icon",
        _ => "application/octet-stream",
    }
}

struct RenderedSection {
    title: String,
    html: String,
}

struct PendingImage {
    src: String,
    title_attr: String,
    alt_buf: String,
}

fn push_plain_text(buf: &mut String, event: &Event<'_>) {
    match event {
        Event::Text(text) => buf.push_str(text),
        Event::Code(code) => buf.push_str(code),
        Event::InlineMath(math) => buf.push_str(math),
        Event::DisplayMath(math) => buf.push_str(math),
        Event::FootnoteReference(label) => buf.push_str(label),
        Event::SoftBreak | Event::HardBreak => buf.push(' '),
        _ => {}
    }
}

fn current_target<'a>(html: &'a mut String, paragraph_html: &'a mut Option<String>) -> &'a mut String {
    match paragraph_html {
        Some(buf) => buf,
        None => html,
    }
}

fn is_escaped_byte(text: &str, index: usize) -> bool {
    let bytes = text.as_bytes();
    let mut count = 0usize;
    let mut cursor = index;
    while cursor > 0 {
        cursor -= 1;
        if bytes[cursor] == b'\\' {
            count += 1;
        } else {
            break;
        }
    }
    count % 2 == 1
}

fn contains_cjk_text_or_punctuation(text: &str) -> bool {
    text.chars().any(|ch| {
        matches!(
            ch,
            '\u{2E80}'..='\u{2EFF}'
                | '\u{2F00}'..='\u{2FDF}'
                | '\u{3000}'..='\u{303F}'
                | '\u{3040}'..='\u{30FF}'
                | '\u{3100}'..='\u{312F}'
                | '\u{31A0}'..='\u{31BF}'
                | '\u{31F0}'..='\u{31FF}'
                | '\u{3400}'..='\u{4DBF}'
                | '\u{4E00}'..='\u{9FFF}'
                | '\u{AC00}'..='\u{D7AF}'
                | '\u{F900}'..='\u{FAFF}'
                | '\u{FF00}'..='\u{FFEF}'
        )
    })
}

fn is_invalid_inline_math_candidate(expr: &str) -> bool {
    let trimmed = expr.trim();
    if trimmed.is_empty() {
        return true;
    }
    if contains_cjk_text_or_punctuation(trimmed) {
        return true;
    }
    matches!(
        trimmed.chars().last(),
        Some('+' | '-' | '–' | '—' | '−' | '=' | '/' | '*' | ':' | ';' | ',' | '→' | '←' | '↔' | '⇒' | '⇐' | '⇔')
    )
}

fn append_inline_math_html(buf: &mut String, text: &str, math_font_size: f64, font_dir: &str) {
    let bytes = text.as_bytes();
    let mut plain_start = 0usize;
    let mut i = 0usize;

    while i < bytes.len() {
        if bytes[i] == b'$' && !is_escaped_byte(text, i) {
            let prev_is_dollar = i > 0 && bytes[i - 1] == b'$';
            let next_is_dollar = i + 1 < bytes.len() && bytes[i + 1] == b'$';
            if prev_is_dollar || next_is_dollar {
                i += 1;
                continue;
            }

            let mut matched: Option<(usize, String)> = None;
            let mut j = i + 1;
            while j < bytes.len() {
                if bytes[j] == b'$' && !is_escaped_byte(text, j) {
                    let prev_close_is_dollar = j > 0 && bytes[j - 1] == b'$';
                    let next_close_is_dollar = j + 1 < bytes.len() && bytes[j + 1] == b'$';
                    if !prev_close_is_dollar && !next_close_is_dollar {
                        let expr = text[i + 1..j].trim();
                        if !expr.is_empty() && !expr.contains('\n') && !is_invalid_inline_math_candidate(expr) {
                            if let Ok(svg) = latex_to_svg(expr, false, math_font_size, font_dir) {
                                matched = Some((j, svg));
                                break;
                            }
                        }
                    }
                }
                j += 1;
            }

            if let Some((end, svg)) = matched {
                buf.push_str(&html_escape(&text[plain_start..i]));
                buf.push_str("<span class=\"math-inline\">");
                buf.push_str(&svg);
                buf.push_str("</span>");
                plain_start = end + 1;
                i = end + 1;
                continue;
            }
        }
        i += 1;
    }

    buf.push_str(&html_escape(&text[plain_start..]));
}

fn render_display_math_paragraph(plain: &str, math_font_size: f64, font_dir: &str) -> Option<String> {
    let trimmed = plain.trim();
    if trimmed.len() < 4 || !trimmed.starts_with("$$") || !trimmed.ends_with("$$") {
        return None;
    }

    let inner = trimmed[2..trimmed.len() - 2].trim();
    if inner.is_empty() || inner.contains("$$") {
        return None;
    }

    let svg = latex_to_svg(inner, true, math_font_size, font_dir).ok()?;
    Some(format!("<div class=\"math-display\">{svg}</div>"))
}

fn render_markdown(
    source: &str,
    base_dir: &Path,
    math_font_size: f64,
    font_dir: &str,
    ss: &SyntaxSet,
    ts: &ThemeSet,
) -> Result<RenderedSection> {
    let mut opts = Options::empty();
    opts.insert(Options::ENABLE_TABLES);
    opts.insert(Options::ENABLE_STRIKETHROUGH);
    opts.insert(Options::ENABLE_TASKLISTS);
    opts.insert(Options::ENABLE_FOOTNOTES);

    let parser = MdParser::new_ext(source, opts);
    let events: Vec<Event> = parser.collect();

    let mut html = String::new();
    let mut title = String::new();
    let mut first_heading = true;

    let theme = ts
        .themes
        .get("base16-ocean.dark")
        .or_else(|| ts.themes.values().next())
        .context("No theme found")?;

    enum Context {
        Normal,
        CodeBlock { lang: String, buf: String },
        Heading { level: u32, buf: String, image: Option<PendingImage> },
        Image(PendingImage),
    }

    let mut ctx = Context::Normal;
    let mut in_table_head = false;
    let mut table_alignments: Vec<pulldown_cmark::Alignment> = Vec::new();
    let mut table_col_index: usize = 0;
    let mut paragraph_html: Option<String> = None;
    let mut paragraph_plain: Option<String> = None;
    let mut paragraph_is_plain = true;

    for event in &events {
        match &mut ctx {
            Context::CodeBlock { lang, buf } => match event {
                Event::Text(text) => buf.push_str(text),
                Event::End(TagEnd::CodeBlock) => {
                    let lang_str = lang
                        .split_whitespace()
                        .next()
                        .unwrap_or("")
                        .to_ascii_lowercase();
                    let buf_str = buf.clone();
                    ctx = Context::Normal;
                    match lang_str.as_str() {
                        "math" | "latex" => {
                            match latex_to_svg(buf_str.trim(), true, math_font_size, font_dir) {
                                Ok(svg) => {
                                    html.push_str("<div class=\"math-display\">");
                                    html.push_str(&svg);
                                    html.push_str("</div>\n");
                                }
                                Err(_) => {
                                    html.push_str("<pre class=\"math-error\"><code>");
                                    html.push_str(&html_escape(&buf_str));
                                    html.push_str("</code></pre>\n");
                                }
                            }
                        }
                        "mermaid" | "mmd" => {
                            match render_mermaid(&buf_str) {
                                Ok(rendered) => html.push_str(&rendered),
                                Err(_) => html.push_str(&mermaid_error_html(&buf_str)),
                            }
                        }
                        _ => {
                            let highlighted = if lang_str.is_empty() {
                                format!("<pre><code>{}</code></pre>\n", html_escape(&buf_str))
                            } else {
                                highlight_code(&buf_str, &lang_str, ss, theme)
                            };
                            html.push_str(&highlighted);
                        }
                    }
                }
                _ => {}
            },

            Context::Heading { level, buf, image } => {
                if let Some(pending) = image {
                    match event {
                        Event::End(TagEnd::Image) => {
                            let alt = html_escape(&pending.alt_buf);
                            buf.push_str(&format!("<img src=\"{}\" alt=\"{}\"{}>", pending.src.as_str(), alt, pending.title_attr.as_str()));
                            *image = None;
                        }
                        _ => push_plain_text(&mut pending.alt_buf, event),
                    }
                } else {
                    match event {
                        Event::Text(text) => append_inline_math_html(buf, text, math_font_size, font_dir),
                        Event::Code(code) => {
                            buf.push_str("<code>");
                            buf.push_str(&html_escape(code));
                            buf.push_str("</code>");
                        }
                        Event::Start(Tag::Emphasis) => buf.push_str("<em>"),
                        Event::End(TagEnd::Emphasis) => buf.push_str("</em>"),
                        Event::Start(Tag::Strong) => buf.push_str("<strong>"),
                        Event::End(TagEnd::Strong) => buf.push_str("</strong>"),
                        Event::Start(Tag::Strikethrough) => buf.push_str("<del>"),
                        Event::End(TagEnd::Strikethrough) => buf.push_str("</del>"),
                        Event::Start(Tag::Link { dest_url, title: link_title, .. }) => {
                            let title_attr = if link_title.is_empty() {
                                String::new()
                            } else {
                                format!(" title=\"{}\"", html_escape(link_title))
                            };
                            buf.push_str(&format!("<a href=\"{}\"{title_attr}>", html_escape(dest_url)));
                        }
                        Event::End(TagEnd::Link) => buf.push_str("</a>"),
                        Event::Start(Tag::Image { dest_url, title: img_title, .. }) => {
                            let src = image_to_data_uri(dest_url, base_dir);
                            let title_attr = if img_title.is_empty() {
                                String::new()
                            } else {
                                format!(" title=\"{}\"", html_escape(img_title))
                            };
                            *image = Some(PendingImage {
                                src: html_escape(&src),
                                title_attr,
                                alt_buf: String::new(),
                            });
                        }
                        Event::InlineMath(math) => {
                            if let Ok(svg) = latex_to_svg(math, false, math_font_size, font_dir) {
                                buf.push_str("<span class=\"math-inline\">");
                                buf.push_str(&svg);
                                buf.push_str("</span>");
                            }
                        }
                        Event::Html(raw) => buf.push_str(raw),
                        Event::InlineHtml(raw) => buf.push_str(raw),
                        Event::SoftBreak => buf.push(' '),
                        Event::HardBreak => buf.push(' '),
                        Event::End(TagEnd::Heading(_)) => {
                            let lvl = *level;
                            let plain = strip_html_tags(buf);
                            let id = slugify(&plain);
                            if first_heading && lvl == 1 {
                                title = plain.clone();
                                first_heading = false;
                            }
                            html.push_str(&format!("<h{lvl} id=\"{id}\">{buf}</h{lvl}>\n"));
                            ctx = Context::Normal;
                        }
                        _ => {}
                    }
                }
            }

            Context::Image(pending) => match event {
                Event::End(TagEnd::Image) => {
                    let alt = html_escape(&pending.alt_buf);
                    current_target(&mut html, &mut paragraph_html)
                        .push_str(&format!("<img src=\"{}\" alt=\"{}\"{}>", pending.src.as_str(), alt, pending.title_attr.as_str()));
                    ctx = Context::Normal;
                }
                _ => push_plain_text(&mut pending.alt_buf, event),
            },

            Context::Normal => match event {
                Event::Start(Tag::CodeBlock(kind)) => {
                    let lang = match kind {
                        pulldown_cmark::CodeBlockKind::Fenced(l) => l.to_string(),
                        pulldown_cmark::CodeBlockKind::Indented => String::new(),
                    };
                    ctx = Context::CodeBlock { lang, buf: String::new() };
                }

                Event::Start(Tag::Heading { level, .. }) => {
                    ctx = Context::Heading { level: *level as u32, buf: String::new(), image: None };
                }

                Event::Start(Tag::Image { dest_url, title: img_title, .. }) => {
                    if paragraph_html.is_some() {
                        paragraph_is_plain = false;
                    }
                    let src = image_to_data_uri(dest_url, base_dir);
                    let title_attr = if img_title.is_empty() {
                        String::new()
                    } else {
                        format!(" title=\"{}\"", html_escape(img_title))
                    };
                    ctx = Context::Image(PendingImage {
                        src: html_escape(&src),
                        title_attr,
                        alt_buf: String::new(),
                    });
                }

                Event::InlineMath(math) => {
                    if paragraph_html.is_some() {
                        paragraph_is_plain = false;
                    }
                    let target = current_target(&mut html, &mut paragraph_html);
                    match latex_to_svg(math, false, math_font_size, font_dir) {
                        Ok(svg) => {
                            target.push_str("<span class=\"math-inline\">");
                            target.push_str(&svg);
                            target.push_str("</span>");
                        }
                        Err(_) => {
                            target.push_str("<code class=\"math-error\">");
                            target.push_str(&html_escape(math));
                            target.push_str("</code>");
                        }
                    }
                }
                Event::DisplayMath(math) => {
                    if paragraph_html.is_some() {
                        paragraph_is_plain = false;
                    }
                    let target = current_target(&mut html, &mut paragraph_html);
                    match latex_to_svg(math, true, math_font_size, font_dir) {
                        Ok(svg) => {
                            target.push_str("<div class=\"math-display\">");
                            target.push_str(&svg);
                            target.push_str("</div>\n");
                        }
                        Err(_) => {
                            target.push_str("<div class=\"math-error\"><code>");
                            target.push_str(&html_escape(math));
                            target.push_str("</code></div>\n");
                        }
                    }
                }

                Event::Start(Tag::Link { dest_url, title: link_title, .. }) => {
                    if paragraph_html.is_some() {
                        paragraph_is_plain = false;
                    }
                    let title_attr = if link_title.is_empty() {
                        String::new()
                    } else {
                        format!(" title=\"{}\"", html_escape(link_title))
                    };
                    current_target(&mut html, &mut paragraph_html)
                        .push_str(&format!("<a href=\"{}\"{title_attr}>", html_escape(dest_url)));
                }
                Event::End(TagEnd::Link) => {
                    if paragraph_html.is_some() {
                        paragraph_is_plain = false;
                    }
                    current_target(&mut html, &mut paragraph_html).push_str("</a>");
                }

                Event::Html(raw) => {
                    if paragraph_html.is_some() {
                        paragraph_is_plain = false;
                    }
                    current_target(&mut html, &mut paragraph_html).push_str(raw);
                }
                Event::InlineHtml(raw) => {
                    if paragraph_html.is_some() {
                        paragraph_is_plain = false;
                    }
                    current_target(&mut html, &mut paragraph_html).push_str(raw);
                }

                Event::Start(Tag::Paragraph) => {
                    paragraph_html = Some(String::new());
                    paragraph_plain = Some(String::new());
                    paragraph_is_plain = true;
                }
                Event::End(TagEnd::Paragraph) => {
                    let rendered = paragraph_html.take().unwrap_or_default();
                    let plain = paragraph_plain.take().unwrap_or_default();
                    if paragraph_is_plain {
                        if let Some(display_html) = render_display_math_paragraph(&plain, math_font_size, font_dir) {
                            html.push_str(&display_html);
                            html.push('\n');
                        } else {
                            html.push_str("<p>");
                            html.push_str(&rendered);
                            html.push_str("</p>\n");
                        }
                    } else {
                        html.push_str("<p>");
                        html.push_str(&rendered);
                        html.push_str("</p>\n");
                    }
                    paragraph_is_plain = true;
                }

                Event::Start(Tag::BlockQuote(_)) => html.push_str("<blockquote>\n"),
                Event::End(TagEnd::BlockQuote(_)) => html.push_str("</blockquote>\n"),

                Event::Start(Tag::List(None)) => html.push_str("<ul>\n"),
                Event::End(TagEnd::List(false)) => html.push_str("</ul>\n"),
                Event::Start(Tag::List(Some(start))) => {
                    if *start == 1 {
                        html.push_str("<ol>\n");
                    } else {
                        html.push_str(&format!("<ol start=\"{start}\">\n"));
                    }
                }
                Event::End(TagEnd::List(true)) => html.push_str("</ol>\n"),

                Event::Start(Tag::Item) => html.push_str("<li>"),
                Event::End(TagEnd::Item) => html.push_str("</li>\n"),

                Event::Start(Tag::Table(aligns)) => {
                    table_alignments = aligns.to_vec();
                    table_col_index = 0;
                    html.push_str("<div class=\"table-wrap\"><table>\n");
                }
                Event::End(TagEnd::Table) => {
                    table_alignments.clear();
                    html.push_str("</table></div>\n");
                }
                Event::Start(Tag::TableHead) => {
                    in_table_head = true;
                    html.push_str("<thead>\n");
                }
                Event::End(TagEnd::TableHead) => {
                    in_table_head = false;
                    html.push_str("</thead>\n");
                }
                Event::Start(Tag::TableRow) => {
                    table_col_index = 0;
                    html.push_str("<tr>\n");
                }
                Event::End(TagEnd::TableRow) => html.push_str("</tr>\n"),
                Event::Start(Tag::TableCell) => {
                    let align_class = table_alignments
                        .get(table_col_index)
                        .map(|a| match a {
                            pulldown_cmark::Alignment::Left => " class=\"left\"",
                            pulldown_cmark::Alignment::Right => " class=\"right\"",
                            pulldown_cmark::Alignment::Center => " class=\"center\"",
                            pulldown_cmark::Alignment::None => "",
                        })
                        .unwrap_or("");
                    if in_table_head {
                        html.push_str(&format!("<th{align_class}>"));
                    } else {
                        html.push_str(&format!("<td{align_class}>"));
                    }
                }
                Event::End(TagEnd::TableCell) => {
                    if in_table_head {
                        html.push_str("</th>\n");
                    } else {
                        html.push_str("</td>\n");
                    }
                    table_col_index += 1;
                }

                Event::Start(Tag::Emphasis) => {
                    if paragraph_html.is_some() {
                        paragraph_is_plain = false;
                    }
                    current_target(&mut html, &mut paragraph_html).push_str("<em>");
                }
                Event::End(TagEnd::Emphasis) => {
                    if paragraph_html.is_some() {
                        paragraph_is_plain = false;
                    }
                    current_target(&mut html, &mut paragraph_html).push_str("</em>");
                }
                Event::Start(Tag::Strong) => {
                    if paragraph_html.is_some() {
                        paragraph_is_plain = false;
                    }
                    current_target(&mut html, &mut paragraph_html).push_str("<strong>");
                }
                Event::End(TagEnd::Strong) => {
                    if paragraph_html.is_some() {
                        paragraph_is_plain = false;
                    }
                    current_target(&mut html, &mut paragraph_html).push_str("</strong>");
                }
                Event::Start(Tag::Strikethrough) => {
                    if paragraph_html.is_some() {
                        paragraph_is_plain = false;
                    }
                    current_target(&mut html, &mut paragraph_html).push_str("<del>");
                }
                Event::End(TagEnd::Strikethrough) => {
                    if paragraph_html.is_some() {
                        paragraph_is_plain = false;
                    }
                    current_target(&mut html, &mut paragraph_html).push_str("</del>");
                }

                Event::Code(code) => {
                    if let Some(plain) = paragraph_plain.as_mut() {
                        plain.push_str(code);
                        paragraph_is_plain = false;
                    }
                    let target = current_target(&mut html, &mut paragraph_html);
                    target.push_str("<code>");
                    target.push_str(&html_escape(code));
                    target.push_str("</code>");
                }

                Event::Text(text) => {
                    if let Some(plain) = paragraph_plain.as_mut() {
                        plain.push_str(text);
                    }
                    append_inline_math_html(current_target(&mut html, &mut paragraph_html), text, math_font_size, font_dir);
                }

                Event::SoftBreak => {
                    if let Some(plain) = paragraph_plain.as_mut() {
                        plain.push('\n');
                        current_target(&mut html, &mut paragraph_html).push('\n');
                    } else {
                        html.push('\n');
                    }
                }
                Event::HardBreak => {
                    if let Some(plain) = paragraph_plain.as_mut() {
                        plain.push('\n');
                        paragraph_is_plain = false;
                        current_target(&mut html, &mut paragraph_html).push_str("<br>\n");
                    } else {
                        html.push_str("<br>\n");
                    }
                }
                Event::Rule => html.push_str("<hr>\n"),

                Event::TaskListMarker(checked) => {
                    if paragraph_html.is_some() {
                        paragraph_is_plain = false;
                    }
                    let target = current_target(&mut html, &mut paragraph_html);
                    if *checked {
                        target.push_str("<input type=\"checkbox\" checked disabled> ");
                    } else {
                        target.push_str("<input type=\"checkbox\" disabled> ");
                    }
                }

                Event::Start(Tag::FootnoteDefinition(label)) => {
                    html.push_str(&format!(
                        "<div class=\"footnote\" id=\"fn-{}\"><sup>{}</sup> ",
                        html_escape(label),
                        html_escape(label)
                    ));
                }
                Event::End(TagEnd::FootnoteDefinition) => html.push_str("</div>\n"),
                Event::FootnoteReference(label) => {
                    if let Some(plain) = paragraph_plain.as_mut() {
                        plain.push_str(label);
                        paragraph_is_plain = false;
                    }
                    current_target(&mut html, &mut paragraph_html).push_str(&format!(
                        "<sup><a href=\"#fn-{}\">{}</a></sup>",
                        html_escape(label),
                        html_escape(label)
                    ));
                }

                _ => {}
            },
        }
    }

    Ok(RenderedSection { title, html })
}

fn highlight_code(code: &str, lang: &str, ss: &SyntaxSet, theme: &syntect::highlighting::Theme) -> String {
    let syntax = ss
        .find_syntax_by_token(lang)
        .or_else(|| ss.find_syntax_by_extension(lang))
        .unwrap_or_else(|| ss.find_syntax_plain_text());

    let mut hl = HighlightLines::new(syntax, theme);
    let mut out = String::from("<pre><code class=\"language-");
    out.push_str(&html_escape(lang));
    out.push_str("\">");

    for line in syntect::util::LinesWithEndings::from(code) {
        match hl.highlight_line(line, ss) {
            Ok(ranges) => {
                match styled_line_to_highlighted_html(&ranges[..], IncludeBackground::No) {
                    Ok(html_line) => out.push_str(&html_line),
                    Err(_) => out.push_str(&html_escape(line)),
                }
            }
            Err(_) => out.push_str(&html_escape(line)),
        }
    }

    out.push_str("</code></pre>\n");
    out
}

fn html_escape(s: &str) -> String {
    s.replace('&', "&amp;")
        .replace('<', "&lt;")
        .replace('>', "&gt;")
        .replace('"', "&quot;")
        .replace('\'', "&#39;")
}

fn strip_html_tags(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    let mut in_tag = false;
    for c in s.chars() {
        match c {
            '<' => in_tag = true,
            '>' => in_tag = false,
            _ if !in_tag => out.push(c),
            _ => {}
        }
    }
    out
}

fn slugify(text: &str) -> String {
    text.to_lowercase()
        .chars()
        .map(|c| if c.is_alphanumeric() || c == '-' { c } else { '-' })
        .collect::<String>()
        .split('-')
        .filter(|s| !s.is_empty())
        .collect::<Vec<_>>()
        .join("-")
}

fn build_html(title: &str, body_sections: &[RenderedSection]) -> String {
    let body_html: String = if body_sections.len() == 1 {
        body_sections[0].html.clone()
    } else {
        body_sections
            .iter()
            .map(|sec| {
                format!(
                    "<section class=\"doc-section\">\n{}</section>\n",
                    sec.html
                )
            })
            .collect()
    };

    format!(
        r#"<!DOCTYPE html>
<html lang="zh-CN">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>{title}</title>
<style>
{css}
</style>
</head>
<body>
<div class="container">
{body_html}
</div>
</body>
</html>"#,
        title = html_escape(title),
        css = CSS,
        body_html = body_html,
    )
}

const CSS: &str = r#"
*, *::before, *::after {
  box-sizing: border-box;
  margin: 0;
  padding: 0;
}

:root {
  --color-bg: #ffffff;
  --color-text: #1a1a2e;
  --color-muted: #6b7280;
  --color-border: #e5e7eb;
  --color-code-bg: #f3f4f6;
  --color-blockquote-border: #3b82f6;
  --color-blockquote-bg: #eff6ff;
  --color-link: #2563eb;
  --color-link-hover: #1d4ed8;
  --color-table-header: #f9fafb;
  --color-table-row-alt: #f9fafb;
  --mermaid-bg: #ffffff;
  --mermaid-fg: #24292f;
  --mermaid-accent: #0969da;
  --mermaid-line: #57606a;
  --mermaid-muted: #57606a;
  --mermaid-surface: #f6f8fa;
  --mermaid-border: #d0d7de;
  --font-sans: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif;
  --font-mono: "JetBrains Mono", "Fira Code", "Cascadia Code", Consolas, "Liberation Mono", monospace;
  --radius: 6px;
  --shadow-sm: 0 1px 3px rgba(0,0,0,0.08);
}

html {
  font-size: 16px;
  -webkit-text-size-adjust: 100%;
}

body {
  font-family: var(--font-sans);
  font-size: 1rem;
  line-height: 1.75;
  color: var(--color-text);
  background: var(--color-bg);
}

.container {
  max-width: 860px;
  margin: 0 auto;
  padding: 3rem 2rem 5rem;
}

.doc-section + .doc-section {
  margin-top: 4rem;
  padding-top: 3rem;
  border-top: 2px solid var(--color-border);
}

h1, h2, h3, h4, h5, h6 {
  font-weight: 700;
  line-height: 1.3;
  margin-top: 2rem;
  margin-bottom: 0.75rem;
  color: #0f172a;
}

h1 { font-size: 2.25rem; margin-top: 0; border-bottom: 2px solid var(--color-border); padding-bottom: 0.5rem; }
h2 { font-size: 1.5rem; border-bottom: 1px solid var(--color-border); padding-bottom: 0.35rem; }
h3 { font-size: 1.25rem; }
h4 { font-size: 1.1rem; }
h5 { font-size: 1rem; }
h6 { font-size: 0.9rem; color: var(--color-muted); }

p {
  margin-bottom: 1rem;
}

a {
  color: var(--color-link);
  text-decoration: none;
}
a:hover {
  color: var(--color-link-hover);
  text-decoration: underline;
}

strong { font-weight: 700; }
em { font-style: italic; }
del { text-decoration: line-through; color: var(--color-muted); }

code {
  font-family: var(--font-mono);
  font-size: 0.875em;
  background: var(--color-code-bg);
  border: 1px solid var(--color-border);
  border-radius: 3px;
  padding: 0.15em 0.4em;
}

pre {
  background: #1e2030;
  color: #c8d3f5;
  border-radius: var(--radius);
  padding: 1.25rem 1.5rem;
  overflow-x: auto;
  margin: 1.25rem 0;
  font-size: 0.875rem;
  line-height: 1.6;
  box-shadow: var(--shadow-sm);
}

pre code {
  background: none;
  border: none;
  padding: 0;
  font-size: inherit;
  color: inherit;
}

blockquote {
  border-left: 4px solid var(--color-blockquote-border);
  background: var(--color-blockquote-bg);
  padding: 0.75rem 1.25rem;
  margin: 1.25rem 0;
  border-radius: 0 var(--radius) var(--radius) 0;
  color: #374151;
}

blockquote p:last-child {
  margin-bottom: 0;
}

ul, ol {
  padding-left: 1.75rem;
  margin-bottom: 1rem;
}

ul { list-style-type: disc; }
ol { list-style-type: decimal; }

li {
  margin-bottom: 0.35rem;
}

li > ul, li > ol {
  margin-top: 0.35rem;
  margin-bottom: 0;
}

.table-wrap {
  overflow-x: auto;
  margin: 1.25rem 0;
  border-radius: var(--radius);
  box-shadow: var(--shadow-sm);
  border: 1px solid var(--color-border);
}

table {
  width: 100%;
  border-collapse: collapse;
  font-size: 0.9375rem;
}

thead {
  background: var(--color-table-header);
}

th {
  font-weight: 600;
  text-align: left;
  padding: 0.65rem 1rem;
  border-bottom: 2px solid var(--color-border);
  white-space: nowrap;
  color: #374151;
}

td {
  padding: 0.6rem 1rem;
  border-bottom: 1px solid var(--color-border);
}

tr:last-child td {
  border-bottom: none;
}

tr:nth-child(even) {
  background: var(--color-table-row-alt);
}

col.left { text-align: left; }
col.right { text-align: right; }
col.center { text-align: center; }

th.left, td.left { text-align: left; }
th.right, td.right { text-align: right; }
th.center, td.center { text-align: center; }

hr {
  border: none;
  border-top: 2px solid var(--color-border);
  margin: 2.5rem 0;
}

img {
  max-width: 100%;
  height: auto;
  border-radius: var(--radius);
  display: block;
  margin: 1rem 0;
}

.math-inline {
  display: inline-flex;
  align-items: center;
  vertical-align: middle;
  margin: 0 0.1em;
}

.math-inline svg {
  vertical-align: middle;
}

.math-display {
  display: flex;
  justify-content: center;
  align-items: center;
  margin: 1.5rem 0;
  overflow-x: auto;
  padding: 0.5rem;
}

.math-error {
  color: #dc2626;
  background: #fef2f2;
  border: 1px solid #fecaca;
  border-radius: 3px;
  padding: 0.15em 0.4em;
}

.mermaid-display {
  margin: 1.75rem 0;
  padding: 1rem;
  overflow-x: auto;
  border: 1px solid color-mix(in srgb, var(--mermaid-border) 85%, transparent);
  border-radius: 14px;
  background:
    radial-gradient(circle at 16px 16px, color-mix(in srgb, var(--mermaid-accent) 10%, transparent) 0 1px, transparent 1px 18px),
    linear-gradient(135deg, color-mix(in srgb, var(--mermaid-surface) 75%, #ffffff), var(--mermaid-bg));
  box-shadow: 0 16px 40px rgba(15, 23, 42, 0.08), 0 1px 3px rgba(15, 23, 42, 0.08);
}

.mermaid-canvas {
  min-width: max-content;
  display: flex;
  justify-content: center;
  padding: 1.25rem;
  border-radius: 10px;
  background: color-mix(in srgb, var(--mermaid-bg) 88%, transparent);
}

.mermaid-display svg {
  max-width: 100%;
  height: auto;
  font-family: var(--font-sans);
  color: var(--mermaid-fg);
}

.mermaid-display svg text,
.mermaid-display svg tspan {
  fill: var(--mermaid-fg);
  font-family: var(--font-sans);
}

.mermaid-display svg path,
.mermaid-display svg line,
.mermaid-display svg polyline {
  stroke-linecap: round;
  stroke-linejoin: round;
}

.mermaid-display svg .node rect,
.mermaid-display svg .node circle,
.mermaid-display svg .node ellipse,
.mermaid-display svg .node polygon,
.mermaid-display svg .node path {
  fill: var(--mermaid-surface);
  stroke: var(--mermaid-border);
  stroke-width: 1.5px;
  filter: drop-shadow(0 6px 14px rgba(15, 23, 42, 0.08));
}

.mermaid-display svg .edgePath path,
.mermaid-display svg .flowchart-link,
.mermaid-display svg .relationshipLine,
.mermaid-display svg .messageLine0,
.mermaid-display svg .messageLine1 {
  stroke: var(--mermaid-line);
  stroke-width: 1.8px;
}

.mermaid-display svg marker path,
.mermaid-display svg marker polygon {
  fill: var(--mermaid-accent);
  stroke: var(--mermaid-accent);
}

.mermaid-display svg .edgeLabel,
.mermaid-display svg .labelBkg,
.mermaid-display svg .messageText,
.mermaid-display svg .actor,
.mermaid-display svg .cluster rect {
  color: var(--mermaid-muted);
}

.mermaid-display svg .cluster rect {
  fill: color-mix(in srgb, var(--mermaid-surface) 78%, transparent);
  stroke: color-mix(in srgb, var(--mermaid-border) 85%, transparent);
  stroke-dasharray: 5 5;
}

.mermaid-error {
  color: #991b1b;
  background: linear-gradient(135deg, #fff7f7, #fff);
  border-color: #fecaca;
}

.mermaid-error pre {
  margin: 0.75rem 0 0;
  background: #450a0a;
}

.footnote {
  font-size: 0.875rem;
  color: var(--color-muted);
  border-top: 1px solid var(--color-border);
  margin-top: 0.35rem;
  padding-top: 0.35rem;
}

input[type="checkbox"] {
  vertical-align: middle;
  margin-right: 0.35rem;
}

@media (max-width: 640px) {
  .container {
    padding: 1.5rem 1rem 3rem;
  }
  h1 { font-size: 1.75rem; }
  h2 { font-size: 1.35rem; }
}

@media print {
  .container { max-width: 100%; padding: 0; }
  pre { white-space: pre-wrap; word-break: break-all; }
  a { color: var(--color-text); }
}
"#;

struct RenderedDocument {
    html: String,
    section_count: usize,
}

fn render_document(args: &CliArgs, title_hint: Option<&Path>) -> Result<RenderedDocument> {
    if args.inputs.is_empty() {
        bail!("Missing required input. Pass --input <FILE>.");
    }

    let ss = SyntaxSet::load_defaults_newlines();
    let ts = ThemeSet::load_defaults();

    let font_dir = find_katex_fonts(args.katex_fonts.as_deref())?;
    eprintln!("Using KaTeX fonts from: {}", font_dir);

    let mut sections: Vec<RenderedSection> = Vec::new();
    let mut doc_title = args.title.clone().unwrap_or_default();

    for input_path in &args.inputs {
        let base_dir = input_path
            .parent()
            .unwrap_or_else(|| Path::new("."))
            .to_path_buf();

        let source = std::fs::read_to_string(input_path)
            .with_context(|| format!("Cannot read {}", input_path.display()))?;

        let section = render_markdown(&source, &base_dir, args.math_font_size, &font_dir, &ss, &ts)
            .with_context(|| format!("Failed to render {}", input_path.display()))?;

        if doc_title.is_empty() && !section.title.is_empty() {
            doc_title = section.title.clone();
        }

        sections.push(section);
    }

    if doc_title.is_empty() {
        doc_title = title_hint
            .and_then(|p| p.file_stem())
            .and_then(|s| s.to_str())
            .or_else(|| args.inputs.first().and_then(|p| p.file_stem()).and_then(|s| s.to_str()))
            .unwrap_or("Document")
            .to_string();
    }

    let section_count = sections.len();
    let html = build_html(&doc_title, &sections);

    Ok(RenderedDocument { html, section_count })
}

fn write_document(args: &CliArgs, output: &Path, title_hint: Option<&Path>) -> Result<usize> {
    let document = render_document(args, title_hint)?;
    std::fs::write(output, document.html.as_bytes())
        .with_context(|| format!("Cannot write {}", output.display()))?;
    Ok(document.section_count)
}

fn sanitize_file_stem(value: &str) -> String {
    let stem = value
        .chars()
        .map(|c| if c.is_ascii_alphanumeric() || c == '-' || c == '_' { c } else { '-' })
        .collect::<String>()
        .split('-')
        .filter(|part| !part.is_empty())
        .collect::<Vec<_>>()
        .join("-");

    if stem.is_empty() {
        "document".to_string()
    } else {
        stem
    }
}

fn default_view_output_path(args: &CliArgs) -> PathBuf {
    let stem = args
        .inputs
        .first()
        .and_then(|p| p.file_stem())
        .and_then(|s| s.to_str())
        .map(sanitize_file_stem)
        .unwrap_or_else(|| "document".to_string());
    let timestamp = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .map(|duration| duration.as_millis())
        .unwrap_or_default();

    std::env::temp_dir().join(format!("pagemd-{stem}-{timestamp}.html"))
}

fn open_in_browser(path: &Path) -> Result<()> {
    let path = path
        .canonicalize()
        .with_context(|| format!("Cannot resolve {}", path.display()))?;

    #[cfg(target_os = "macos")]
    let mut command = {
        let mut command = Command::new("open");
        command.arg(&path);
        command
    };

    #[cfg(target_os = "windows")]
    let mut command = {
        let mut command = Command::new("cmd");
        command.args(["/C", "start", ""]).arg(&path);
        command
    };

    #[cfg(all(unix, not(target_os = "macos")))]
    let mut command = {
        let mut command = Command::new("xdg-open");
        command.arg(&path);
        command
    };

    let status = command
        .status()
        .with_context(|| format!("Cannot open {}", path.display()))?;
    if !status.success() {
        bail!("Failed to open {}", path.display());
    }

    Ok(())
}

fn run_convert(args: &CliArgs) -> Result<()> {
    let output = args
        .output
        .as_deref()
        .context("Missing required output. Pass --output <FILE>.")?;
    let section_count = write_document(args, output, Some(output))?;

    eprintln!(
        "Written {} section(s) -> {}",
        section_count,
        output.display()
    );

    Ok(())
}

fn run_view(args: &CliArgs) -> Result<()> {
    let output = args.output.clone().unwrap_or_else(|| default_view_output_path(args));
    let title_hint = args.output.as_deref();
    let section_count = write_document(args, &output, title_hint)?;
    open_in_browser(&output)?;

    eprintln!(
        "Opened {} section(s) -> {}",
        section_count,
        output.display()
    );

    Ok(())
}

fn main() -> Result<()> {
    let cli = Cli::parse();

    match cli.command {
        Some(Commands::View(args)) => run_view(&args),
        None => run_convert(&cli.args),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn render_html(source: &str) -> String {
        let ss = SyntaxSet::load_defaults_newlines();
        let ts = ThemeSet::load_defaults();
        render_markdown(source, Path::new("."), 16.0, "", &ss, &ts)
            .unwrap()
            .html
    }

    fn math_inline_count(html: &str) -> usize {
        html.matches("class=\"math-inline\"").count()
    }

    fn mermaid_count(html: &str) -> usize {
        html.matches("class=\"mermaid-display\"").count()
    }

    #[test]
    fn currency_sentence_with_cjk_text_stays_plain() {
        let html = render_html("（$21 发行价，融资 $2.08 亿）");
        assert!(html.contains("<p>（$21 发行价，融资 $2.08 亿）</p>"));
        assert_eq!(math_inline_count(&html), 0);
    }

    #[test]
    fn currency_and_bold_currency_do_not_merge_into_math() {
        let html = render_html("但合并营业利润因 $738M 减值几乎归零；OCF **$710M**");
        assert!(html.contains("$738M"));
        assert!(html.contains("<strong>$710M</strong>"));
        assert_eq!(math_inline_count(&html), 0);
    }

    #[test]
    fn currency_range_stays_plain() {
        let html = render_html("品牌溢价（售价 $40–$60）");
        assert!(html.contains("<p>品牌溢价（售价 $40–$60）</p>"));
        assert_eq!(math_inline_count(&html), 0);
    }

    #[test]
    fn eps_sequence_with_arrows_stays_plain() {
        let html = render_html("（EPS：$8.71→$12.79→$15.88）");
        assert!(html.contains("<p>（EPS：$8.71→$12.79→$15.88）</p>"));
        assert_eq!(math_inline_count(&html), 0);
    }

    #[test]
    fn actual_inline_and_display_math_still_render() {
        let html = render_html("真公式 $x+y$\n\n**$x+y$**\n\n$$x+y$$");
        assert_eq!(math_inline_count(&html), 2);
        assert_eq!(html.matches("class=\"math-display\"").count(), 1);
        assert!(html.contains("<strong><span class=\"math-inline\">"));
    }

    #[test]
    fn mermaid_code_block_renders_svg() {
        let html = render_html("```mermaid\nflowchart LR\n  A[Start] --> B[End]\n```\n");
        assert_eq!(mermaid_count(&html), 1);
        assert!(html.contains("<svg"));
        assert!(!html.contains("language-mermaid"));
    }
}
